**Question 1: What is Logistic Regression, and how does it differ from Linear Regression?**

ans:**Logistic** **Regression** is supervised learning  primely used in machine Learning.

**Key Differences Between Logistic Regression and Linear Regression:**


- **purpose** : In **Logistic** **Regression** ,predicts probability of binary outcome.
 - In **Linear** **Regression** , predicts continuous numerical values.

**Question 2: Explain the role of the Sigmoid function in Logistic Regression.**

ans:The **sigmoid** **function** is transform the linear equation into probability value between 0 and 1.

   z = 1/(1+e^-z)




**Question 3: What is Regularization in Logistic Regression and why is it needed?**

ans:**Regularization** is technique used to **prevent** **overfitting** in machine learning.

**why is it needed?**

- **L1(lasso)**:lasso is for feature selection . .
- **l2(Ridge)**: Ridge is for the reducing the overfitting.



**Question 4: What are some common evaluation metrics for classification models, and why are they important?**

ans:Evaluation metrics help us measure the performance of a classification model.

1.**confusion** **Matrix**:Table showing TP ,TN,fn,FP.



**Question 5: Write a Python program that loads a CSV file into a Pandas DataFrame, splits into train/test sets, trains a Logistic Regression model, and prints its accuracy.**

In [1]:
import pandas as pd

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.datasets import load_breast_cancer

In [4]:
#load breast cancer dataset
data = load_breast_cancer()

In [5]:
X = pd.DataFrame(data.data,columns=data.feature_names)

In [6]:
y = data.target

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
#train test split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
#train logistic Regression model
model = LogisticRegression()

In [9]:
from sklearn.model_selection import GridSearchCV

In [14]:
#finding best  c value and penalty

parmeter = {"penalty":("l1","l2","elasticnet"),"C" : [1,10,20,30]}

GSC = GridSearchCV(model,param_grid=parmeter,cv=5)


In [16]:
GSC.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20, 30],
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [17]:
GSC.best_estimator_

LogisticRegression(C=20)

In [18]:
GSC.best_params_

{'C': 20, 'penalty': 'l2'}

In [20]:
model = LogisticRegression(C=20,penalty="l2")

In [21]:
model.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=20)

In [22]:
#y prediction values
y_pred = model.predict(X_test)

In [23]:
#its accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9649122807017544

**Question 6: Write a Python program to train a Logistic Regression model using L2 regularization (Ridge) and print the model coefficients and accuracy.**

ans:the above code same for this Question


**Question 7: Write a Python program to train a Logistic Regression model for multiclass classification using multi_class='ovr' and print the classification report.**

In [24]:
from sklearn.datasets import make_classification

In [25]:
X,y = make_classification(n_samples=1000,n_features=10,n_redundant=5,n_informative=5,n_classes=3,random_state=1)

In [26]:
#train test split

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.42,random_state=42)

In [29]:
#train multi Logistic Regression model

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
model_multi = LogisticRegression(multi_class='ovr',solver='lbfgs')

In [32]:
model_multi.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [34]:
y_pred = model_multi.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[100   8  34]
 [ 38 104  14]
 [  8  27  87]]
0.6928571428571428
              precision    recall  f1-score   support

           0       0.68      0.70      0.69       142
           1       0.75      0.67      0.71       156
           2       0.64      0.71      0.68       122

    accuracy                           0.69       420
   macro avg       0.69      0.69      0.69       420
weighted avg       0.70      0.69      0.69       420



**Question 8: Write a Python program to apply GridSearchCV to tune C and penalty hyperparameters for Logistic Regression and print the best parameters and validation accuracy.**

In [36]:
# the 5th question answer for the 8th question


**Question 9: Write a Python program to standardize the features before training Logistic Regression and compare the model's accuracy with and without scaling.**

In [37]:

import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer # Using Breast Cancer dataset
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Load the Breast Cancer dataset from sklearn
print("Loading Breast Cancer dataset from sklearn...")
cancer = load_breast_cancer()
X, y = cancer.data, cancer.target

print(f"Dataset shape: {X.shape}")
print(f"Classes: {cancer.target_names}")
print(f"Class distribution: {np.bincount(y)}")

# Split into train/test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"\nTraining set shape: {X_train.shape}")
print(f"Test set shape: {X_test.shape}")

# --- Train model WITHOUT scaling ---
print("\nTraining Logistic Regression model WITHOUT scaling...")
model_no_scale = LogisticRegression(random_state=42, max_iter=1000, solver='liblinear') # Use a suitable solver
model_no_scale.fit(X_train, y_train)
y_pred_no_scale = model_no_scale.predict(X_test)
accuracy_no_scale = accuracy_score(y_test, y_pred_no_scale)

print(f"Accuracy WITHOUT scaling: {accuracy_no_scale:.4f} ({accuracy_no_scale*100:.2f}%)")

# --- Train model WITH scaling ---
print("\nStandardizing features...")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Training Logistic Regression model WITH scaling...")
model_scaled = LogisticRegression(random_state=42, max_iter=1000, solver='liblinear')
model_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = model_scaled.predict(X_test_scaled)
accuracy_scaled = accuracy_score(y_test, y_pred_scaled)

print(f"Accuracy WITH scaling:    {accuracy_scaled:.4f} ({accuracy_scaled*100:.2f}%)")

# --- Comparison ---
print("\nComparison of Accuracy:")
print(f"  Without Scaling: {accuracy_no_scale:.4f}")
print(f"  With Scaling:    {accuracy_scaled:.4f}")


Loading Breast Cancer dataset from sklearn...
Dataset shape: (569, 30)
Classes: ['malignant' 'benign']
Class distribution: [212 357]

Training set shape: (455, 30)
Test set shape: (114, 30)

Training Logistic Regression model WITHOUT scaling...
Accuracy WITHOUT scaling: 0.9561 (95.61%)

Standardizing features...
Training Logistic Regression model WITH scaling...
Accuracy WITH scaling:    0.9825 (98.25%)

Comparison of Accuracy:
  Without Scaling: 0.9561
  With Scaling:    0.9825
